### ISSUE TITLE
Feature Request: Release Version filter improvements

### ISSUE THREAD

**Issue by jeefy** [kubernetes-sigs/release-notes#106]
Couple thoughts to put out there.

- I think it makes sense to reverse-sort the versions in the version filter. Newest at the top. Thoughts?

- The more Y stream releases we do, the more it might make sense to have a collapsable list so you can select "1.15" and then be able to filter the Z stream releases. Thoughts?

**Comment by saschagrunert** [comment]
I think both would be valuable additions and should not be that hard to implement. I can go for it in the next couple of weeks if you want to. :)

**Comment by jeefy** [comment]
All yours!

**Comment by saschagrunert** [comment]
The first part of the implementation is here: https://github.com/kubernetes-sigs/release-notes/pull/108
