### ISSUE TITLE
Add v1.20 release notes

### ISSUE THREAD

**Issue by sftim** [kubernetes-sigs/release-notes#216]
The version selector on https://relnotes.k8s.io/ does not yet list the recent v1.20.0 release of Kubernetes.

**Comment by puerco** [comment]
Thanks for reporting this @sftim, it seems the update to the website was overlooked amid the end of release frenzy.

/cc @wilsonehusin

**Comment by wilsonehusin** [comment]
oops yeah we missed this. thanks a lot for flagging @sftim and covering it @puerco!
