### ISSUE TITLE
Feature Request: Add keyword search

### ISSUE THREAD

**Issue by FingerLiu** [kubernetes-sigs/release-notes#236]
keyword search,it will be greate if we can do keyword search release-note !

**Comment by justaugustus** [comment]
/help
cc: @kubernetes-sigs/release-engineering

**Comment by Akshit42-hue** [comment]
@FingerLiu Can you please assign this issue to me

**Comment by Akshit42-hue** [comment]
Search release-note instead of Search that's the only change I want to do am I right ?
@saschagrunert

**Comment by saschagrunert** [comment]
@Akshit42-hue hm, we already have a way to select the badges as kind of keywords, so I'm now wondering what the intention of this enhancement was. :thinking:
