### ISSUE TITLE
Filter by "deprecation"

### ISSUE THREAD

**Issue by pbnj** [kubernetes-sigs/release-notes#241]
It would be great if release notes supported `deprecation` tags so it can be used in filters.

**Comment by saschagrunert** [comment]
Hey @pbnj, you can click on the "deprecation" label which should result filtering by them: https://relnotes.k8s.io/?kinds=deprecation

Does this fulfill your use case?

**Comment by pbnj** [comment]
@saschagrunert - yes, it does. I don't know how I missed this when I searched for it. Thank you.
