### ISSUE TITLE
Website is slow - enable site analytics?

### ISSUE THREAD

**Issue by ashnehete** [kubernetes-sigs/release-notes#566]
The website has become very slow and will keep on getting slower with every new release since all release notes are fetched before any content is shown to the user.

[PageSpeed Insights - relnotes.k8s.io](https://pagespeed.web.dev/analysis/https-relnotes-k8s-io/y37ez5otc8?form_factor=desktop)

One possible solution is implement [SSR](https://angular.io/guide/universal) but it looks like a major undertaking. I was wondering if we have any stats/analytics on the usage of the website. Or is there a way to do an user survey to understand if the slow website is really a problem?

cc: @saschagrunert @reylejano

**Comment by saschagrunert** [comment]
Hey, I think having kind of an async loading of the actual release notes JSON would make things faster.

**Comment by ashnehete** [comment]
I was just thinking the same. Maybe we can load the latest release first and render. Then continue loading the others in the background. I think this might be easier to implement than SSR.
