### ISSUE TITLE
Hamburger menu doesn’t work on Mobile Safari

### ISSUE THREAD

**Issue by omkensey** [kubernetes-sigs/release-notes#72]
On Mobile Safari, the hamburger menu at upper right doesn’t do anything (it looks greyed out).

**Comment by unguiculus** [comment]
Neither does it do anything on Chrome and Firefox on my Pixel 2XL (Android).

**Comment by anvithks** [comment]
Neither on Chrome on OnePlus 7 pro.

**Comment by saschagrunert** [comment]
Hey @omkensey, thank for the report. Let me check what's going on here.
