### ISSUE TITLE
Feature Request: Improved tag filtering on https://relnotes.k8s.io/

### ISSUE THREAD

**Issue by KnoxAnderson** [kubernetes-sigs/release-notes#73]
Right now the search between the different sections uses **OR** logic for filtering tags. 

It would be nice if the filtering logic was 

**OR** within sections (areas, kinds, sigs)

& 

**AND** between sections

This would allow the ability to do something like show me all security features in this release. 

Area = Secure AND Kind = Feature

**Comment by saschagrunert** [comment]
@KnoxAnderson thank you for the suggestion :pray: 

@jeefy do we want to change the filter logic generally that way? We could also add a dedicated syntax for AND/OR related filtering.

**Comment by jeefy** [comment]
Tough call. The reason it was defaulted to `OR` in the first place was we wanted to let people filter as much as possible but ensure they don't miss anything (meaning, the person is the final filter)

If we try to build a dedicated syntax (which would be super cool) I don't know how we could reflect it with how the filter UI currently is (and vice versa)

The biggest thing we can't compromise is the ability to copy/paste the URLs generated. I also think this should be kept in mind, but hold off on any changes till after the 1.16 release.
