### ISSUE TITLE
Feature request: RSS feed

### ISSUE THREAD

**Issue by immanuelfodor** [kubernetes-sigs/release-notes#80]
Hi Everyone, 

It would be great to have an RSS feed of the changes displayed on the site to enable automated notifications based on 3rd party services. I looked into the HTML source, and it is fully JS-based, so I tried to convert it with a self-hosted [HRSS](https://hipstercat.fr/gogs/hipstercat/hrss)  instance, but the JS won't load and displays an empty page. Even if you include a static `index.xml` file as an RSS feed (like e.g., [Hugo](https://gohugo.io/templates/rss/) does) that would be automatically rebuilt on new changes, it would greatly improve the experience and accessibility. 

Cheers, Immánuel

**Comment by immanuelfodor** [comment]
The [assets folder](https://github.com/kubernetes-sigs/release-notes/tree/master/src/assets) contains the structured data in separate files that would be needed for an unified RSS feed. _(The JSON files are also available publicly thruogh the website but also separately, which means there is no way to track it if a new release comes out + everyone must do their own JSON to RSS XML transformation.)_

**Comment by saschagrunert** [comment]
Hey @immanuelfodor, good idea. I think we could built this into the usual development workflow somehow.

**Comment by immanuelfodor** [comment]
I think here it is where the JSON files are generated: 
https://github.com/kubernetes-sigs/release-notes/blob/master/generate.sh#L17
Sadly, the tool only supports JSON and Markdown output:
https://github.com/kubernetes/release/tree/master/cmd/release-notes#why-formats-are-supported
So it should be done with a tool like `jq` or something else after the JSON files are put. For example, merging and converting the JSON files with `jq` to the [JSON feed spec](https://jsonfeed.org/version/1) and then with some Bash magic/Python/Go to an XML RSS feed. This way another intermediate format would be available for use. But it's just thinking out loud throwing in some ideas :)

**Comment by saschagrunert** [comment]
> I think here it is where the JSON files are generated:
> https://github.com/kubernetes-sigs/release-notes/blob/master/generate.sh#L17
> Sadly, the tool only supports JSON and Markdown output:
> https://github.com/kubernetes/release/tree/master/cmd/release-notes#why-formats-are-supported
> So it should be done with a tool like `jq` or something else after the JSON files are put. For example, merging and converting the JSON files with `jq` to the [JSON feed spec](https://jsonfeed.org/version/1) and then with some Bash magic/Python/Go to an XML RSS feed. This way another intermediate format would be available for use. But it's just thinking out loud throwing in some ideas :)

Yeah I thought about something similar. We're really free to manipulate the incoming data here since we can include any node package into the project. I think we also would need no real diff'ing if we stick to the current approach of exchanging complete files as assets.

**Comment by saschagrunert** [comment]
@immanuelfodor I'm right now not planning to work on this. Do you consider contributing a PR to make it work? :)

**Comment by immanuelfodor** [comment]
I don't have the resources to dive down the rabbit hole and I've made peace with depending on https://kubernetes.io/docs/setup/release/notes/ myself to check it regularly, so I'm keeping this open if somebody can solve this for us. It's just sad that for such a high rated tool as k8s there is no feed support to follow the releases other than the https://kubernetes.io/feed.xml Hugo blog RSS mixed into other posts. If you're aware of other sources, please share but I could only find this ticket in Google 😀

**Comment by saschagrunert** [comment]
Sounds good, thank you for the update!
