### ISSUE TITLE
Document "Additional documentation" best practices

### ISSUE THREAD

**Issue by mrbobbytables** [kubernetes-sigs/release-notes#91]
When adding additional documentation to an issue (linking to a KEP etc) the links should point to specific commit instead of `tree/master`. The relevant information for that release note is _point in time_ whereas linking to the current master will not reflect the state of that information for that specific release.

**Comment by saschagrunert** [comment]
Hey @jeefy @mrbobbytables :wave:, where do you think is a good place for having such information? I would put them directly at the [PR template](https://github.com/kubernetes/kubernetes/blob/391906f/.github/PULL_REQUEST_TEMPLATE.md).

**Comment by mrbobbytables** [comment]
+1. That'd be the easiest and likely broadest way to let folk know what they should do.
